query StratzGetConstants {
  constants {
    heroes {
      id
      name
      localizedName: displayName
      stats {
        primaryAttribute
        attackType
      }
      roles {
        roleId
      }
    }
    items {
      id
      name
      localizedName: displayName
    }
    abilities {
      id
      name
      language {
        displayName
      }
    }
    gameModes {
      id
      name
    }
    regions {
      id
      name
      localizedName: displayName
    }
  }
}

query StratzGetHeroStatsDay(
  $heroIds: [Short!]
  $bracketIds: [RankBracket!]
  $positionIds: [MatchPlayerPositionType!]
) {
  heroStats {
    stats: winDay(
      heroIds: $heroIds
      bracketIds: $bracketIds
      positionIds: $positionIds
      take: 400
      skip: 0
      groupBy: TIME
    ) {
      heroId
      matchCount
      winCount
      period: day
    }
  }
}

query StratzGetHeroStatsWeek(
  $heroIds: [Short!]
  $bracketIds: [RankBracket!]
  $positionIds: [MatchPlayerPositionType!]
) {
  heroStats {
    stats: winWeek(
      heroIds: $heroIds
      bracketIds: $bracketIds
      positionIds: $positionIds
      take: 60
      skip: 0
      groupBy: TIME
    ) {
      heroId
      matchCount
      winCount
      period: week
    }
  }
}

query StratzGetHeroStatsMonth(
  $heroIds: [Short!]
  $bracketIds: [RankBracket!]
  $positionIds: [MatchPlayerPositionType!]
) {
  heroStats {
    stats: winMonth(
      heroIds: $heroIds
      bracketIds: $bracketIds
      positionIds: $positionIds
      take: 18
      skip: 0
      groupBy: TIME
    ) {
      heroId
      matchCount
      winCount
      period: month
    }
  }
}
