fragment MatchSummaryFields on MatchType {
  id
  startDateTime
  durationSeconds
  didRadiantWin
  radiantKills
  direKills
  gameModeId: gameMode
  lobbyTypeId: lobbyType
  regionId
  leagueId
  gameVersionId
  parsedDateTime
  statsDateTime
}

fragment MatchPlayerFields on MatchPlayerType {
  steamAccountId
  heroId
  isRadiant
  playerSlot
  kills
  deaths
  assists
  networth
  level
  imp
}

fragment MatchStandardFields on MatchType {
  ...MatchSummaryFields
  players {
    ...MatchPlayerFields
  }
  playbackData {
    buildingEvents {
      time
      type
      isRadiant
      npcId
    }
    roshanEvents {
      time
    }
    towerDeathEvents {
      time
      radiant
      dire
    }
  }
}

fragment MatchFullFields on MatchType {
  ...MatchStandardFields
  playbackData {
    runeEvents {
      time
      action
      rune
    }
    wardEvents {
      time
      action
      wardType
      fromPlayer
    }
  }
}

query StratzGetMatchSummary($id: Long!) {
  match(id: $id) {
    ...MatchSummaryFields
    players {
      ...MatchPlayerFields
    }
  }
}

query StratzGetMatchStandard($id: Long!) {
  match(id: $id) {
    ...MatchStandardFields
  }
}

query StratzGetMatchFull($id: Long!) {
  match(id: $id) {
    ...MatchFullFields
  }
}

query StratzGetMatchBatchSummary(
  $id0: Long!
  $id1: Long!
  $id2: Long!
  $id3: Long!
  $id4: Long!
) {
  match0: match(id: $id0) {
    ...MatchSummaryFields
    players {
      ...MatchPlayerFields
    }
  }
  match1: match(id: $id1) {
    ...MatchSummaryFields
    players {
      ...MatchPlayerFields
    }
  }
  match2: match(id: $id2) {
    ...MatchSummaryFields
    players {
      ...MatchPlayerFields
    }
  }
  match3: match(id: $id3) {
    ...MatchSummaryFields
    players {
      ...MatchPlayerFields
    }
  }
  match4: match(id: $id4) {
    ...MatchSummaryFields
    players {
      ...MatchPlayerFields
    }
  }
}

query StratzGetMatchBatchStandard(
  $id0: Long!
  $id1: Long!
  $id2: Long!
  $id3: Long!
  $id4: Long!
) {
  match0: match(id: $id0) {
    ...MatchStandardFields
  }
  match1: match(id: $id1) {
    ...MatchStandardFields
  }
  match2: match(id: $id2) {
    ...MatchStandardFields
  }
  match3: match(id: $id3) {
    ...MatchStandardFields
  }
  match4: match(id: $id4) {
    ...MatchStandardFields
  }
}

query StratzGetMatchBatchFull(
  $id0: Long!
  $id1: Long!
  $id2: Long!
  $id3: Long!
  $id4: Long!
) {
  match0: match(id: $id0) {
    ...MatchFullFields
  }
  match1: match(id: $id1) {
    ...MatchFullFields
  }
  match2: match(id: $id2) {
    ...MatchFullFields
  }
  match3: match(id: $id3) {
    ...MatchFullFields
  }
  match4: match(id: $id4) {
    ...MatchFullFields
  }
}

query StratzGetMatchesSummary($ids: [Long!]!) {
  matches(ids: $ids) {
    ...MatchSummaryFields
    players {
      ...MatchPlayerFields
    }
  }
}

query StratzGetMatchesStandard($ids: [Long!]!) {
  matches(ids: $ids) {
    ...MatchStandardFields
  }
}

query StratzGetMatchesFull($ids: [Long!]!) {
  matches(ids: $ids) {
    ...MatchFullFields
  }
}
