// Code generated by contractgen; DO NOT EDIT.

package contracts

const ContractVersion = "1.0.0-draft.3"
const MCPProtocolVersion = "2025-11-25"
const SchemaDraft = "https://json-schema.org/draft/2020-12/schema"

func RawGraphQLAllowedRootFields() []string {
	return []string{
		"constants",
		"guild",
		"heroStats",
		"leaderboard",
		"league",
		"leagues",
		"live",
		"match",
		"matches",
		"player",
		"players",
		"team",
		"teams",
	}
}

func RawGraphQLDeniedRootFields() []string {
	return []string{
		"plus",
		"stratz",
		"vendor",
		"yogurt",
	}
}

type ToolResult[T any] struct {
	Kind       string      `json:"kind"`
	Data       *T          `json:"data,omitempty"`
	Summary    *string     `json:"summary,omitempty"`
	Provenance *Provenance `json:"provenance,omitempty"`
	Warnings   []string    `json:"warnings,omitempty"`
	Raw        any         `json:"raw,omitempty"`
	Error      *Error      `json:"error,omitempty"`
	Context    any         `json:"context,omitempty"`
}

type ErrorCode string

const (
	ErrorCodeInvalidArgument             ErrorCode = "INVALID_ARGUMENT"
	ErrorCodeNotFound                    ErrorCode = "NOT_FOUND"
	ErrorCodePrivate                     ErrorCode = "PRIVATE"
	ErrorCodeDataNotReady                ErrorCode = "DATA_NOT_READY"
	ErrorCodeRateLimited                 ErrorCode = "RATE_LIMITED"
	ErrorCodeUpstreamTimeout             ErrorCode = "UPSTREAM_TIMEOUT"
	ErrorCodeUpstreamNetworkError        ErrorCode = "UPSTREAM_NETWORK_ERROR"
	ErrorCodeUpstreamTLSError            ErrorCode = "UPSTREAM_TLS_ERROR"
	ErrorCodeUpstreamWAFBlocked          ErrorCode = "UPSTREAM_WAF_BLOCKED"
	ErrorCodeUpstreamProtocolError       ErrorCode = "UPSTREAM_PROTOCOL_ERROR"
	ErrorCodeUpstreamPartialError        ErrorCode = "UPSTREAM_PARTIAL_ERROR"
	ErrorCodeUpstreamError               ErrorCode = "UPSTREAM_ERROR"
	ErrorCodeResponseTooLarge            ErrorCode = "RESPONSE_TOO_LARGE"
	ErrorCodeQueryDocumentTooLarge       ErrorCode = "QUERY_DOCUMENT_TOO_LARGE"
	ErrorCodeQueryVariablesTooLarge      ErrorCode = "QUERY_VARIABLES_TOO_LARGE"
	ErrorCodeQueryDepthExceeded          ErrorCode = "QUERY_DEPTH_EXCEEDED"
	ErrorCodeQueryAliasLimitExceeded     ErrorCode = "QUERY_ALIAS_LIMIT_EXCEEDED"
	ErrorCodeQueryFieldLimitExceeded     ErrorCode = "QUERY_FIELD_LIMIT_EXCEEDED"
	ErrorCodeQueryComplexityExceeded     ErrorCode = "QUERY_COMPLEXITY_EXCEEDED"
	ErrorCodeQueryListLimitRequired      ErrorCode = "QUERY_LIST_LIMIT_REQUIRED"
	ErrorCodeQueryListLimitExceeded      ErrorCode = "QUERY_LIST_LIMIT_EXCEEDED"
	ErrorCodeQueryOperationLimitExceeded ErrorCode = "QUERY_OPERATION_LIMIT_EXCEEDED"
	ErrorCodeQueryOperationNotAllowed    ErrorCode = "QUERY_OPERATION_NOT_ALLOWED"
	ErrorCodeIntrospectionDisabled       ErrorCode = "INTROSPECTION_DISABLED"
	ErrorCodeRequestBudgetExceeded       ErrorCode = "REQUEST_BUDGET_EXCEEDED"
	ErrorCodeAuthenticationFailed        ErrorCode = "AUTHENTICATION_FAILED"
	ErrorCodeCursorInvalid               ErrorCode = "CURSOR_INVALID"
	ErrorCodeCursorExpired               ErrorCode = "CURSOR_EXPIRED"
	ErrorCodeCacheUnavailable            ErrorCode = "CACHE_UNAVAILABLE"
	ErrorCodeInternalError               ErrorCode = "INTERNAL_ERROR"
)

type ConstantRecord struct {
	ID            string         `json:"id"`
	LocalizedName *string        `json:"localized_name"`
	Metadata      map[string]any `json:"metadata"`
	Name          string         `json:"name"`
}

type DateTime string

type DetailLevel string

const (
	DetailLevelSummary  DetailLevel = "summary"
	DetailLevelStandard DetailLevel = "standard"
	DetailLevelFull     DetailLevel = "full"
)

type EconomyPoint struct {
	DireExperience    *int64 `json:"dire_experience"`
	DireNetworth      *int64 `json:"dire_networth"`
	RadiantExperience *int64 `json:"radiant_experience"`
	RadiantNetworth   *int64 `json:"radiant_networth"`
	TimeSeconds       int64  `json:"time_seconds"`
}

type Error struct {
	Code        ErrorCode        `json:"code"`
	Details     map[string]any   `json:"details"`
	FailedInput any              `json:"failed_input,omitempty"`
	Message     string           `json:"message"`
	RetryAfter  NullableDateTime `json:"retry_after"`
	Retryable   bool             `json:"retryable"`
}

type ErrorContext MatchAvailabilityContext

type ErrorResult struct {
	Context *ErrorContext `json:"context,omitempty"`
	Error   Error         `json:"error"`
	Kind    string        `json:"kind"`
}

type Fight struct {
	DireKills      int64 `json:"dire_kills"`
	EndTimeSeconds int64 `json:"end_time_seconds"`
	Participants   []struct {
		AccountID *string `json:"account_id"`
		Deaths    int64   `json:"deaths"`
		HeroID    int64   `json:"hero_id"`
		Kills     int64   `json:"kills"`
		Team      string  `json:"team"`
	} `json:"participants"`
	RadiantKills         int64  `json:"radiant_kills"`
	RadiantNetworthDelta *int64 `json:"radiant_networth_delta"`
	StartTimeSeconds     int64  `json:"start_time_seconds"`
}

type Hero struct {
	AttackType       *string  `json:"attack_type"`
	HeroID           int64    `json:"hero_id"`
	LocalizedName    *string  `json:"localized_name"`
	Name             string   `json:"name"`
	PrimaryAttribute *string  `json:"primary_attribute"`
	Roles            []string `json:"roles"`
	Slug             string   `json:"slug"`
}

type HeroBreakdown struct {
	Name       string   `json:"name"`
	PickRate   *float64 `json:"pick_rate"`
	SampleSize int64    `json:"sample_size"`
	WinRate    *float64 `json:"win_rate"`
}

type HeroIdentifier any

type HeroRelation struct {
	Advantage  *float64 `json:"advantage"`
	HeroID     int64    `json:"hero_id"`
	SampleSize int64    `json:"sample_size"`
	WinRate    *float64 `json:"win_rate"`
}

type League struct {
	EndsAt   NullableDateTime `json:"ends_at"`
	LeagueID string           `json:"league_id"`
	Name     string           `json:"name"`
	Region   *string          `json:"region"`
	StartsAt NullableDateTime `json:"starts_at"`
	Status   *string          `json:"status"`
	Tier     *string          `json:"tier"`
}

type LiveMatch struct {
	DireTeamName    *string           `json:"dire_team_name"`
	DurationSeconds *int64            `json:"duration_seconds"`
	GameModeID      *int64            `json:"game_mode_id"`
	League          *League           `json:"league"`
	MatchID         MatchID           `json:"match_id"`
	Players         []LiveMatchPlayer `json:"players"`
	RadiantTeamName *string           `json:"radiant_team_name"`
	SpectatorCount  *int64            `json:"spectator_count"`
	StartedAt       NullableDateTime  `json:"started_at"`
}

type LiveMatchPlayer struct {
	AccountID *string `json:"account_id"`
	Assists   int64   `json:"assists"`
	Deaths    int64   `json:"deaths"`
	HeroID    *int64  `json:"hero_id"`
	Kills     int64   `json:"kills"`
	Level     *int64  `json:"level"`
	Networth  *int64  `json:"networth"`
	Position  int64   `json:"position"`
	Team      string  `json:"team"`
	Won       *bool   `json:"won"`
}

type Match struct {
	DireScore       *int64           `json:"dire_score"`
	DurationSeconds *int64           `json:"duration_seconds"`
	Economy         []EconomyPoint   `json:"economy,omitempty"`
	Fights          []Fight          `json:"fights,omitempty"`
	GameModeID      *int64           `json:"game_mode_id"`
	LeagueID        *string          `json:"league_id"`
	LobbyTypeID     *int64           `json:"lobby_type_id"`
	MatchID         MatchID          `json:"match_id"`
	Objectives      []TimelineEvent  `json:"objectives,omitempty"`
	ParseStatus     string           `json:"parse_status"`
	PatchID         *string          `json:"patch_id"`
	Players         []MatchPlayer    `json:"players"`
	RadiantScore    *int64           `json:"radiant_score"`
	RadiantWin      *bool            `json:"radiant_win"`
	RegionID        *int64           `json:"region_id"`
	StartedAt       NullableDateTime `json:"started_at"`
	Timeline        []TimelineEvent  `json:"timeline,omitempty"`
}

type MatchAvailabilityContext struct {
	Match                MatchSummary `json:"match"`
	RequestedDetailLevel DetailLevel  `json:"requested_detail_level"`
	Type                 string       `json:"type"`
}

type MatchID string

type MatchPlayer struct {
	AccountID *string  `json:"account_id"`
	Assists   int64    `json:"assists"`
	Deaths    int64    `json:"deaths"`
	HeroID    int64    `json:"hero_id"`
	Imp       *float64 `json:"imp"`
	Kills     int64    `json:"kills"`
	Level     *int64   `json:"level"`
	Networth  *int64   `json:"networth"`
	Position  int64    `json:"position"`
	Team      string   `json:"team"`
	Won       bool     `json:"won"`
}

type MatchSummary struct {
	DireScore       *int64           `json:"dire_score"`
	DurationSeconds *int64           `json:"duration_seconds"`
	GameModeID      *int64           `json:"game_mode_id"`
	LeagueID        *string          `json:"league_id"`
	LobbyTypeID     *int64           `json:"lobby_type_id"`
	MatchID         MatchID          `json:"match_id"`
	ParseStatus     string           `json:"parse_status"`
	PatchID         *string          `json:"patch_id"`
	RadiantScore    *int64           `json:"radiant_score"`
	RadiantWin      *bool            `json:"radiant_win"`
	RegionID        *int64           `json:"region_id"`
	StartedAt       NullableDateTime `json:"started_at"`
}

type NullableDateTime = *DateTime

type PageInfo struct {
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

type PaginationInput struct {
	Cursor *string `json:"cursor,omitempty"`
	Limit  *int64  `json:"limit,omitempty"`
}

type Player struct {
	AccountID   string           `json:"account_id"`
	AvatarURL   *string          `json:"avatar_url"`
	DisplayName *string          `json:"display_name"`
	IsPrivate   bool             `json:"is_private"`
	LastMatchAt NullableDateTime `json:"last_match_at,omitempty"`
	MatchCount  *int64           `json:"match_count,omitempty"`
	Rank        *struct {
		LeaderboardRank *int64 `json:"leaderboard_rank"`
		RankTier        *int64 `json:"rank_tier"`
	} `json:"rank"`
	SteamID64 *string `json:"steam_id64"`
	WinCount  *int64  `json:"win_count,omitempty"`
}

type PlayerIdentifier string

type Provenance struct {
	Cache struct {
		AgeSeconds *int64 `json:"age_seconds"`
		Status     string `json:"status"`
	} `json:"cache"`
	DateRange *struct {
		From NullableDateTime `json:"from"`
		To   NullableDateTime `json:"to"`
	} `json:"date_range"`
	DetailLevel *DetailLevel `json:"detail_level"`
	Operation   string       `json:"operation"`
	Patch       *struct {
		ID   *string `json:"id"`
		Name *string `json:"name"`
	} `json:"patch"`
	RateLimits []struct {
		Limit     *int64           `json:"limit"`
		Remaining *int64           `json:"remaining"`
		ResetAt   NullableDateTime `json:"reset_at"`
		Source    *string          `json:"source"`
		Window    string           `json:"window"`
	} `json:"rate_limits"`
	RetrievedAt   DateTime `json:"retrieved_at"`
	SchemaVersion string   `json:"schema_version"`
}

type SuccessBase struct {
	Data       any        `json:"data"`
	Kind       string     `json:"kind"`
	Provenance Provenance `json:"provenance"`
	Raw        any        `json:"raw,omitempty"`
	Summary    *string    `json:"summary"`
	Warnings   []string   `json:"warnings"`
}

type TimelineEvent struct {
	AccountID   *string `json:"account_id"`
	HeroID      *int64  `json:"hero_id"`
	Team        *string `json:"team"`
	TimeSeconds int64   `json:"time_seconds"`
	Type        string  `json:"type"`
	Value       any     `json:"value"`
}

type StratzBatchGetHeroesRequest struct {
	DetailLevel *DetailLevel     `json:"detail_level,omitempty"`
	Fresh       *bool            `json:"fresh,omitempty"`
	Heroes      []HeroIdentifier `json:"heroes"`
	IncludeRaw  *bool            `json:"include_raw,omitempty"`
}

type StratzBatchGetHeroesData struct {
	Items []Hero `json:"items"`
}

type StratzBatchGetHeroesResponse ToolResult[StratzBatchGetHeroesData]

type StratzBatchGetMatchesRequest struct {
	DetailLevel *DetailLevel `json:"detail_level,omitempty"`
	Fresh       *bool        `json:"fresh,omitempty"`
	IncludeRaw  *bool        `json:"include_raw,omitempty"`
	MatchIds    []MatchID    `json:"match_ids"`
}

type StratzBatchGetMatchesData struct {
	Items []Match `json:"items"`
}

type StratzBatchGetMatchesResponse ToolResult[StratzBatchGetMatchesData]

type StratzBatchGetPlayersRequest struct {
	DetailLevel *DetailLevel       `json:"detail_level,omitempty"`
	Fresh       *bool              `json:"fresh,omitempty"`
	IncludeRaw  *bool              `json:"include_raw,omitempty"`
	PlayerIds   []PlayerIdentifier `json:"player_ids"`
}

type StratzBatchGetPlayersData struct {
	Items []Player `json:"items"`
}

type StratzBatchGetPlayersResponse ToolResult[StratzBatchGetPlayersData]

type StratzExecuteGraphQLRequest struct {
	Cache           *bool          `json:"cache,omitempty"`
	CacheTTLSeconds *int64         `json:"cache_ttl_seconds,omitempty"`
	Fresh           *bool          `json:"fresh,omitempty"`
	OperationName   *string        `json:"operation_name,omitempty"`
	Query           string         `json:"query"`
	Variables       map[string]any `json:"variables,omitempty"`
}

type StratzExecuteGraphQLData struct {
	GraphQL struct {
		Data       any              `json:"data"`
		Errors     []map[string]any `json:"errors"`
		Extensions *map[string]any  `json:"extensions"`
	} `json:"graphql"`
	HTTPStatus int64 `json:"http_status"`
	Partial    bool  `json:"partial"`
}

type StratzExecuteGraphQLResponse ToolResult[StratzExecuteGraphQLData]

type StratzGetConstantsRequest struct {
	Fresh      *bool  `json:"fresh,omitempty"`
	IncludeRaw *bool  `json:"include_raw,omitempty"`
	Type       string `json:"type"`
}

type StratzGetConstantsData struct {
	Items []ConstantRecord `json:"items"`
	Type  string           `json:"type"`
}

type StratzGetConstantsResponse ToolResult[StratzGetConstantsData]

type StratzGetHeroRequest struct {
	DetailLevel *DetailLevel   `json:"detail_level,omitempty"`
	Fresh       *bool          `json:"fresh,omitempty"`
	Hero        HeroIdentifier `json:"hero"`
	IncludeRaw  *bool          `json:"include_raw,omitempty"`
}

type StratzGetHeroData Hero

type StratzGetHeroResponse ToolResult[StratzGetHeroData]

type StratzGetHeroStatsRequest struct {
	Fresh            *bool          `json:"fresh,omitempty"`
	From             *DateTime      `json:"from,omitempty"`
	Hero             HeroIdentifier `json:"hero"`
	IncludeMatchups  *bool          `json:"include_matchups,omitempty"`
	IncludeRaw       *bool          `json:"include_raw,omitempty"`
	IncludeSynergies *bool          `json:"include_synergies,omitempty"`
	Lane             *string        `json:"lane,omitempty"`
	PatchID          *string        `json:"patch_id,omitempty"`
	RankBracket      *string        `json:"rank_bracket,omitempty"`
	Role             *string        `json:"role,omitempty"`
	To               *DateTime      `json:"to,omitempty"`
}

type StratzGetHeroStatsData struct {
	BanRate    *float64        `json:"ban_rate"`
	HeroID     int64           `json:"hero_id"`
	Lanes      []HeroBreakdown `json:"lanes"`
	Matchups   []HeroRelation  `json:"matchups"`
	PickRate   *float64        `json:"pick_rate"`
	Roles      []HeroBreakdown `json:"roles"`
	SampleSize int64           `json:"sample_size"`
	Synergies  []HeroRelation  `json:"synergies"`
	WinRate    *float64        `json:"win_rate"`
}

type StratzGetHeroStatsResponse ToolResult[StratzGetHeroStatsData]

type StratzGetLeagueRequest struct {
	DetailLevel *DetailLevel `json:"detail_level,omitempty"`
	Fresh       *bool        `json:"fresh,omitempty"`
	IncludeRaw  *bool        `json:"include_raw,omitempty"`
	LeagueID    string       `json:"league_id"`
}

type StratzGetLeagueData League

type StratzGetLeagueResponse ToolResult[StratzGetLeagueData]

type StratzGetMatchRequest struct {
	DetailLevel *DetailLevel `json:"detail_level,omitempty"`
	Fresh       *bool        `json:"fresh,omitempty"`
	IncludeRaw  *bool        `json:"include_raw,omitempty"`
	MatchID     MatchID      `json:"match_id"`
}

type StratzGetMatchData Match

type StratzGetMatchResponse ToolResult[StratzGetMatchData]

type StratzGetPlayerRequest struct {
	DetailLevel *DetailLevel     `json:"detail_level,omitempty"`
	Fresh       *bool            `json:"fresh,omitempty"`
	IncludeRaw  *bool            `json:"include_raw,omitempty"`
	PlayerID    PlayerIdentifier `json:"player_id"`
}

type StratzGetPlayerData Player

type StratzGetPlayerResponse ToolResult[StratzGetPlayerData]

type StratzListLeagueMatchesRequest struct {
	Cursor      *string      `json:"cursor,omitempty"`
	DetailLevel *DetailLevel `json:"detail_level,omitempty"`
	Fresh       *bool        `json:"fresh,omitempty"`
	From        *DateTime    `json:"from,omitempty"`
	IncludeRaw  *bool        `json:"include_raw,omitempty"`
	LeagueID    string       `json:"league_id"`
	Limit       *int64       `json:"limit,omitempty"`
	PatchID     *string      `json:"patch_id,omitempty"`
	To          *DateTime    `json:"to,omitempty"`
}

type StratzListLeagueMatchesData struct {
	Items []MatchSummary `json:"items"`
	Page  PageInfo       `json:"page"`
}

type StratzListLeagueMatchesResponse ToolResult[StratzListLeagueMatchesData]

type StratzListLeaguesRequest struct {
	Cursor     *string   `json:"cursor,omitempty"`
	Fresh      *bool     `json:"fresh,omitempty"`
	From       *DateTime `json:"from,omitempty"`
	IncludeRaw *bool     `json:"include_raw,omitempty"`
	Limit      *int64    `json:"limit,omitempty"`
	Query      *string   `json:"query,omitempty"`
	Status     *string   `json:"status,omitempty"`
	Tier       *string   `json:"tier,omitempty"`
	To         *DateTime `json:"to,omitempty"`
}

type StratzListLeaguesData struct {
	Items []League `json:"items"`
	Page  PageInfo `json:"page"`
}

type StratzListLeaguesResponse ToolResult[StratzListLeaguesData]

type StratzListLiveMatchesRequest struct {
	Cursor            *string           `json:"cursor,omitempty"`
	Fresh             *bool             `json:"fresh,omitempty"`
	GameModeID        *int64            `json:"game_mode_id,omitempty"`
	GameStates        []string          `json:"game_states,omitempty"`
	Hero              *HeroIdentifier   `json:"hero,omitempty"`
	IncludeRaw        *bool             `json:"include_raw,omitempty"`
	LeagueID          *string           `json:"league_id,omitempty"`
	Limit             *int64            `json:"limit,omitempty"`
	MinimumSpectators *int64            `json:"minimum_spectators,omitempty"`
	PlayerID          *PlayerIdentifier `json:"player_id,omitempty"`
	Sort              *string           `json:"sort,omitempty"`
	TeamID            *string           `json:"team_id,omitempty"`
	Tiers             []string          `json:"tiers,omitempty"`
}

type StratzListLiveMatchesData struct {
	Items []LiveMatch `json:"items"`
	Page  PageInfo    `json:"page"`
}

type StratzListLiveMatchesResponse ToolResult[StratzListLiveMatchesData]

type StratzListPlayerMatchesRequest struct {
	Cursor                 *string          `json:"cursor,omitempty"`
	DetailLevel            *DetailLevel     `json:"detail_level,omitempty"`
	Fresh                  *bool            `json:"fresh,omitempty"`
	From                   *DateTime        `json:"from,omitempty"`
	GameModeID             *int64           `json:"game_mode_id,omitempty"`
	Hero                   *HeroIdentifier  `json:"hero,omitempty"`
	IncludeRaw             *bool            `json:"include_raw,omitempty"`
	Limit                  *int64           `json:"limit,omitempty"`
	LobbyTypeID            *int64           `json:"lobby_type_id,omitempty"`
	MinimumDurationSeconds *int64           `json:"minimum_duration_seconds,omitempty"`
	PatchID                *string          `json:"patch_id,omitempty"`
	PlayerID               PlayerIdentifier `json:"player_id"`
	Result                 *string          `json:"result,omitempty"`
	Role                   *string          `json:"role,omitempty"`
	To                     *DateTime        `json:"to,omitempty"`
}

type StratzListPlayerMatchesData struct {
	Items []MatchSummary `json:"items"`
	Page  PageInfo       `json:"page"`
}

type StratzListPlayerMatchesResponse ToolResult[StratzListPlayerMatchesData]

type StratzServerInfoRequest struct{}

type StratzServerInfoData struct {
	CacheStatus        string         `json:"cache_status"`
	Limits             map[string]any `json:"limits"`
	MCPProtocolVersion string         `json:"mcp_protocol_version"`
	SchemaVersion      string         `json:"schema_version"`
	ServerVersion      string         `json:"server_version"`
	UpstreamStatus     string         `json:"upstream_status"`
}

type StratzServerInfoResponse ToolResult[StratzServerInfoData]

var generatedDefinitions = []Definition{
	{Name: "stratz_batch_get_heroes", Description: "Get up to 25 heroes atomically; any item failure or ambiguity fails the entire batch.", InputSchemaPath: "generated/schemas/stratz_batch_get_heroes.input.json", OutputSchemaPath: "generated/schemas/stratz_batch_get_heroes.output.json", InputExamplePath: "generated/examples/stratz_batch_get_heroes.input.json", OutputExamplePath: "generated/examples/stratz_batch_get_heroes.output.json", ProtocolFixturePath: "generated/protocol/stratz_batch_get_heroes.json"},
	{Name: "stratz_batch_get_matches", Description: "Get up to 25 matches atomically; any item failure fails the entire batch.", InputSchemaPath: "generated/schemas/stratz_batch_get_matches.input.json", OutputSchemaPath: "generated/schemas/stratz_batch_get_matches.output.json", InputExamplePath: "generated/examples/stratz_batch_get_matches.input.json", OutputExamplePath: "generated/examples/stratz_batch_get_matches.output.json", ProtocolFixturePath: "generated/protocol/stratz_batch_get_matches.json"},
	{Name: "stratz_batch_get_players", Description: "Get up to 25 players atomically; any item failure fails the entire batch.", InputSchemaPath: "generated/schemas/stratz_batch_get_players.input.json", OutputSchemaPath: "generated/schemas/stratz_batch_get_players.output.json", InputExamplePath: "generated/examples/stratz_batch_get_players.input.json", OutputExamplePath: "generated/examples/stratz_batch_get_players.output.json", ProtocolFixturePath: "generated/protocol/stratz_batch_get_players.json"},
	{Name: "stratz_execute_graphql", Description: "Execute one guarded GraphQL query against an approved STRATZ root field using JSON-compatible variables.", InputSchemaPath: "generated/schemas/stratz_execute_graphql.input.json", OutputSchemaPath: "generated/schemas/stratz_execute_graphql.output.json", InputExamplePath: "generated/examples/stratz_execute_graphql.input.json", OutputExamplePath: "generated/examples/stratz_execute_graphql.output.json", ProtocolFixturePath: "generated/protocol/stratz_execute_graphql.json"},
	{Name: "stratz_get_constants", Description: "Get one explicit class of STRATZ/Dota reference constants, or all classes when requested.", InputSchemaPath: "generated/schemas/stratz_get_constants.input.json", OutputSchemaPath: "generated/schemas/stratz_get_constants.output.json", InputExamplePath: "generated/examples/stratz_get_constants.input.json", OutputExamplePath: "generated/examples/stratz_get_constants.output.json", ProtocolFixturePath: "generated/protocol/stratz_get_constants.json"},
	{Name: "stratz_get_hero", Description: "Get normalized hero reference data by numeric ID, exact localized name, or canonical slug.", InputSchemaPath: "generated/schemas/stratz_get_hero.input.json", OutputSchemaPath: "generated/schemas/stratz_get_hero.output.json", InputExamplePath: "generated/examples/stratz_get_hero.input.json", OutputExamplePath: "generated/examples/stratz_get_hero.output.json", ProtocolFixturePath: "generated/protocol/stratz_get_hero.json"},
	{Name: "stratz_get_hero_stats", Description: "Get bounded aggregate hero statistics for a date, patch, rank, role, and lane window.", InputSchemaPath: "generated/schemas/stratz_get_hero_stats.input.json", OutputSchemaPath: "generated/schemas/stratz_get_hero_stats.output.json", InputExamplePath: "generated/examples/stratz_get_hero_stats.input.json", OutputExamplePath: "generated/examples/stratz_get_hero_stats.output.json", ProtocolFixturePath: "generated/protocol/stratz_get_hero_stats.json"},
	{Name: "stratz_get_league", Description: "Get normalized league metadata by exact league ID.", InputSchemaPath: "generated/schemas/stratz_get_league.input.json", OutputSchemaPath: "generated/schemas/stratz_get_league.output.json", InputExamplePath: "generated/examples/stratz_get_league.input.json", OutputExamplePath: "generated/examples/stratz_get_league.output.json", ProtocolFixturePath: "generated/protocol/stratz_get_league.json"},
	{Name: "stratz_get_match", Description: "Get a normalized Dota match with detail-level controlled timelines and replay-derived events.", InputSchemaPath: "generated/schemas/stratz_get_match.input.json", OutputSchemaPath: "generated/schemas/stratz_get_match.output.json", InputExamplePath: "generated/examples/stratz_get_match.input.json", OutputExamplePath: "generated/examples/stratz_get_match.output.json", ProtocolFixturePath: "generated/protocol/stratz_get_match.json"},
	{Name: "stratz_get_player", Description: "Get a normalized STRATZ player profile by account ID, SteamID64, or STRATZ profile URL.", InputSchemaPath: "generated/schemas/stratz_get_player.input.json", OutputSchemaPath: "generated/schemas/stratz_get_player.output.json", InputExamplePath: "generated/examples/stratz_get_player.input.json", OutputExamplePath: "generated/examples/stratz_get_player.output.json", ProtocolFixturePath: "generated/protocol/stratz_get_player.json"},
	{Name: "stratz_list_league_matches", Description: "List matches for a league with bounded date/patch filters and an authenticated opaque cursor.", InputSchemaPath: "generated/schemas/stratz_list_league_matches.input.json", OutputSchemaPath: "generated/schemas/stratz_list_league_matches.output.json", InputExamplePath: "generated/examples/stratz_list_league_matches.input.json", OutputExamplePath: "generated/examples/stratz_list_league_matches.output.json", ProtocolFixturePath: "generated/protocol/stratz_list_league_matches.json"},
	{Name: "stratz_list_leagues", Description: "Search and list STRATZ leagues with bounded filters and an authenticated opaque cursor.", InputSchemaPath: "generated/schemas/stratz_list_leagues.input.json", OutputSchemaPath: "generated/schemas/stratz_list_leagues.output.json", InputExamplePath: "generated/examples/stratz_list_leagues.input.json", OutputExamplePath: "generated/examples/stratz_list_leagues.output.json", ProtocolFixturePath: "generated/protocol/stratz_list_leagues.json"},
	{Name: "stratz_list_live_matches", Description: "List current live matches with bounded filters, sorting, and a short-lived authenticated cursor.", InputSchemaPath: "generated/schemas/stratz_list_live_matches.input.json", OutputSchemaPath: "generated/schemas/stratz_list_live_matches.output.json", InputExamplePath: "generated/examples/stratz_list_live_matches.input.json", OutputExamplePath: "generated/examples/stratz_list_live_matches.output.json", ProtocolFixturePath: "generated/protocol/stratz_list_live_matches.json"},
	{Name: "stratz_list_player_matches", Description: "List normalized matches for a player using bounded filters and an authenticated opaque cursor.", InputSchemaPath: "generated/schemas/stratz_list_player_matches.input.json", OutputSchemaPath: "generated/schemas/stratz_list_player_matches.output.json", InputExamplePath: "generated/examples/stratz_list_player_matches.input.json", OutputExamplePath: "generated/examples/stratz_list_player_matches.output.json", ProtocolFixturePath: "generated/protocol/stratz_list_player_matches.json"},
	{Name: "stratz_server_info", Description: "Return server, protocol, schema, cache, limit, and upstream connectivity information without secrets.", InputSchemaPath: "generated/schemas/stratz_server_info.input.json", OutputSchemaPath: "generated/schemas/stratz_server_info.output.json", InputExamplePath: "generated/examples/stratz_server_info.input.json", OutputExamplePath: "generated/examples/stratz_server_info.output.json", ProtocolFixturePath: "generated/protocol/stratz_server_info.json"},
}
