// Code generated by contractgen; DO NOT EDIT.

package contracts

const ContractVersion = "2.0.0-draft.1"
const MCPProtocolVersion = "2026-07-28"
const SchemaDraft = "https://json-schema.org/draft/2020-12/schema"

func SupportedMCPProtocolVersions() []string {
	return []string{
		"2026-07-28",
		"2025-11-25",
		"2025-06-18",
		"2025-03-26",
		"2024-11-05",
	}
}

func RawGraphQLAllowedRootFields() []string {
	return []string{
		"constants",
		"guild",
		"heroStats",
		"leaderboard",
		"league",
		"leagues",
		"live",
		"match",
		"matches",
		"player",
		"players",
		"team",
		"teams",
	}
}

func RawGraphQLDeniedRootFields() []string {
	return []string{
		"plus",
		"stratz",
		"vendor",
		"yogurt",
	}
}

type ToolResult[T any] struct {
	Kind       string      `json:"kind"`
	Data       *T          `json:"data,omitempty"`
	Summary    *string     `json:"summary,omitempty"`
	Provenance *Provenance `json:"provenance,omitempty"`
	Warnings   []string    `json:"warnings,omitempty"`
	Raw        any         `json:"raw,omitempty"`
	Error      *Error      `json:"error,omitempty"`
	Context    any         `json:"context,omitempty"`
}

type ErrorCode string

const (
	ErrorCodeInvalidArgument             ErrorCode = "INVALID_ARGUMENT"
	ErrorCodeNotFound                    ErrorCode = "NOT_FOUND"
	ErrorCodePrivate                     ErrorCode = "PRIVATE"
	ErrorCodeDataNotReady                ErrorCode = "DATA_NOT_READY"
	ErrorCodeRateLimited                 ErrorCode = "RATE_LIMITED"
	ErrorCodeUpstreamTimeout             ErrorCode = "UPSTREAM_TIMEOUT"
	ErrorCodeUpstreamNetworkError        ErrorCode = "UPSTREAM_NETWORK_ERROR"
	ErrorCodeUpstreamTLSError            ErrorCode = "UPSTREAM_TLS_ERROR"
	ErrorCodeUpstreamWAFBlocked          ErrorCode = "UPSTREAM_WAF_BLOCKED"
	ErrorCodeUpstreamProtocolError       ErrorCode = "UPSTREAM_PROTOCOL_ERROR"
	ErrorCodeUpstreamPartialError        ErrorCode = "UPSTREAM_PARTIAL_ERROR"
	ErrorCodeUpstreamError               ErrorCode = "UPSTREAM_ERROR"
	ErrorCodeResponseTooLarge            ErrorCode = "RESPONSE_TOO_LARGE"
	ErrorCodeQueryDocumentTooLarge       ErrorCode = "QUERY_DOCUMENT_TOO_LARGE"
	ErrorCodeQueryVariablesTooLarge      ErrorCode = "QUERY_VARIABLES_TOO_LARGE"
	ErrorCodeQueryDepthExceeded          ErrorCode = "QUERY_DEPTH_EXCEEDED"
	ErrorCodeQueryAliasLimitExceeded     ErrorCode = "QUERY_ALIAS_LIMIT_EXCEEDED"
	ErrorCodeQueryFieldLimitExceeded     ErrorCode = "QUERY_FIELD_LIMIT_EXCEEDED"
	ErrorCodeQueryComplexityExceeded     ErrorCode = "QUERY_COMPLEXITY_EXCEEDED"
	ErrorCodeQueryListLimitRequired      ErrorCode = "QUERY_LIST_LIMIT_REQUIRED"
	ErrorCodeQueryListLimitExceeded      ErrorCode = "QUERY_LIST_LIMIT_EXCEEDED"
	ErrorCodeQueryOperationLimitExceeded ErrorCode = "QUERY_OPERATION_LIMIT_EXCEEDED"
	ErrorCodeQueryOperationNotAllowed    ErrorCode = "QUERY_OPERATION_NOT_ALLOWED"
	ErrorCodeIntrospectionDisabled       ErrorCode = "INTROSPECTION_DISABLED"
	ErrorCodeRequestBudgetExceeded       ErrorCode = "REQUEST_BUDGET_EXCEEDED"
	ErrorCodeAuthenticationFailed        ErrorCode = "AUTHENTICATION_FAILED"
	ErrorCodeCursorInvalid               ErrorCode = "CURSOR_INVALID"
	ErrorCodeCursorExpired               ErrorCode = "CURSOR_EXPIRED"
	ErrorCodeCacheUnavailable            ErrorCode = "CACHE_UNAVAILABLE"
	ErrorCodeInternalError               ErrorCode = "INTERNAL_ERROR"
)

type CommonControls struct {
	Fresh      *bool `json:"fresh,omitempty"`
	IncludeRaw *bool `json:"include_raw,omitempty"`
}

type Constant struct {
	ID            string         `json:"id"`
	LocalizedName *string        `json:"localized_name"`
	Metadata      map[string]any `json:"metadata"`
	Name          string         `json:"name"`
	Type          string         `json:"type"`
}

type DateTime string

type DetailLevel string

const (
	DetailLevelSummary  DetailLevel = "summary"
	DetailLevelStandard DetailLevel = "standard"
	DetailLevelFull     DetailLevel = "full"
)

type Error struct {
	Code        ErrorCode        `json:"code"`
	Details     map[string]any   `json:"details"`
	FailedInput any              `json:"failed_input,omitempty"`
	Message     string           `json:"message"`
	RetryAfter  NullableDateTime `json:"retry_after"`
	Retryable   bool             `json:"retryable"`
}

type ErrorResult struct {
	Context *MatchAvailabilityContext `json:"context,omitempty"`
	Error   Error                     `json:"error"`
	Kind    string                    `json:"kind"`
}

type Event struct {
	AccountID   *string `json:"account_id"`
	HeroID      *int64  `json:"hero_id"`
	Team        *string `json:"team"`
	TimeSeconds int64   `json:"time_seconds"`
	Type        string  `json:"type"`
	Value       any     `json:"value"`
}

type ExactMatchDetailLevel MatchDetailLevel

type Hero struct {
	AttackType       *string  `json:"attack_type"`
	HeroID           int64    `json:"hero_id"`
	LocalizedName    *string  `json:"localized_name"`
	Name             string   `json:"name"`
	PrimaryAttribute *string  `json:"primary_attribute"`
	Roles            []string `json:"roles"`
	Slug             string   `json:"slug"`
	Statistics       *struct {
		PickRate   *float64 `json:"pick_rate"`
		SampleSize int64    `json:"sample_size"`
		WinRate    *float64 `json:"win_rate"`
	} `json:"statistics,omitempty"`
}

type HeroIdentifier any

type Identifier string

type League struct {
	EndsAt   NullableDateTime `json:"ends_at"`
	LeagueID string           `json:"league_id"`
	Name     string           `json:"name"`
	Region   *string          `json:"region"`
	StartsAt NullableDateTime `json:"starts_at"`
	Status   *string          `json:"status"`
	Tier     *string          `json:"tier"`
}

type LeagueHistoryDetailLevel string

const (
	LeagueHistoryDetailLevelSummary LeagueHistoryDetailLevel = "summary"
)

type LiveMatch struct {
	DireTeamName    *string          `json:"dire_team_name"`
	DurationSeconds *int64           `json:"duration_seconds"`
	GameModeID      *int64           `json:"game_mode_id"`
	League          *League          `json:"league"`
	MatchID         MatchID          `json:"match_id"`
	Players         []LivePlayer     `json:"players"`
	RadiantTeamName *string          `json:"radiant_team_name"`
	SpectatorCount  *int64           `json:"spectator_count"`
	StartedAt       NullableDateTime `json:"started_at"`
}

type LivePlayer struct {
	AccountID *string `json:"account_id"`
	Assists   int64   `json:"assists"`
	Deaths    int64   `json:"deaths"`
	HeroID    *int64  `json:"hero_id"`
	Kills     int64   `json:"kills"`
	Level     *int64  `json:"level"`
	Networth  *int64  `json:"networth"`
	Position  int64   `json:"position"`
	Team      string  `json:"team"`
	Won       *bool   `json:"won"`
}

type Match struct {
	DireScore       *int64           `json:"dire_score"`
	DurationSeconds *int64           `json:"duration_seconds"`
	GameModeID      *int64           `json:"game_mode_id"`
	LeagueID        *string          `json:"league_id"`
	LobbyTypeID     *int64           `json:"lobby_type_id"`
	MatchID         MatchID          `json:"match_id"`
	Objectives      []Event          `json:"objectives,omitempty"`
	ParseStatus     string           `json:"parse_status"`
	PatchID         *string          `json:"patch_id"`
	Players         []MatchPlayer    `json:"players"`
	RadiantScore    *int64           `json:"radiant_score"`
	RadiantWin      *bool            `json:"radiant_win"`
	RegionID        *int64           `json:"region_id"`
	StartedAt       NullableDateTime `json:"started_at"`
	Timeline        []Event          `json:"timeline,omitempty"`
}

type MatchAvailabilityContext struct {
	Match                MatchSummary `json:"match"`
	RequestedDetailLevel DetailLevel  `json:"requested_detail_level"`
	Type                 string       `json:"type"`
}

type MatchDetailLevel string

const (
	MatchDetailLevelSummary  MatchDetailLevel = "summary"
	MatchDetailLevelPlayers  MatchDetailLevel = "players"
	MatchDetailLevelStandard MatchDetailLevel = "standard"
	MatchDetailLevelFull     MatchDetailLevel = "full"
)

type MatchID string

type MatchPlayer struct {
	AccountID *string `json:"account_id"`
	Assists   int64   `json:"assists"`
	Deaths    int64   `json:"deaths"`
	HeroID    *int64  `json:"hero_id"`
	Kills     int64   `json:"kills"`
	Level     *int64  `json:"level"`
	Networth  *int64  `json:"networth"`
	Position  int64   `json:"position"`
	Team      string  `json:"team"`
	Won       *bool   `json:"won"`
}

type MatchSummary struct {
	DireScore       *int64           `json:"dire_score"`
	DurationSeconds *int64           `json:"duration_seconds"`
	GameModeID      *int64           `json:"game_mode_id"`
	LeagueID        *string          `json:"league_id"`
	LobbyTypeID     *int64           `json:"lobby_type_id"`
	MatchID         MatchID          `json:"match_id"`
	ParseStatus     string           `json:"parse_status"`
	PatchID         *string          `json:"patch_id"`
	RadiantScore    *int64           `json:"radiant_score"`
	RadiantWin      *bool            `json:"radiant_win"`
	RegionID        *int64           `json:"region_id"`
	StartedAt       NullableDateTime `json:"started_at"`
}

type NullableDateTime = *DateTime

type Page struct {
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

type Pagination struct {
	Cursor *string `json:"cursor,omitempty"`
	Limit  *int64  `json:"limit,omitempty"`
}

type Player struct {
	AccountID   string           `json:"account_id"`
	AvatarURL   *string          `json:"avatar_url"`
	DisplayName *string          `json:"display_name"`
	IsPrivate   bool             `json:"is_private"`
	LastMatchAt NullableDateTime `json:"last_match_at,omitempty"`
	MatchCount  *int64           `json:"match_count,omitempty"`
	Rank        *struct {
		LeaderboardRank *int64 `json:"leaderboard_rank"`
		RankTier        *int64 `json:"rank_tier"`
	} `json:"rank"`
	Statistics *struct {
		LastMatchAt NullableDateTime `json:"last_match_at"`
		MatchCount  int64            `json:"match_count"`
		WinCount    int64            `json:"win_count"`
	} `json:"statistics,omitempty"`
	SteamID64 *string `json:"steam_id64"`
	WinCount  *int64  `json:"win_count,omitempty"`
}

type PlayerHistoryDetailLevel string

const (
	PlayerHistoryDetailLevelSummary PlayerHistoryDetailLevel = "summary"
	PlayerHistoryDetailLevelPlayers PlayerHistoryDetailLevel = "players"
)

type PlayerMatchSummary struct {
	DireScore       *int64           `json:"dire_score"`
	DurationSeconds *int64           `json:"duration_seconds"`
	GameModeID      *int64           `json:"game_mode_id"`
	LeagueID        *string          `json:"league_id"`
	LobbyTypeID     *int64           `json:"lobby_type_id"`
	MatchID         MatchID          `json:"match_id"`
	ParseStatus     string           `json:"parse_status"`
	PatchID         *string          `json:"patch_id"`
	Player          *MatchPlayer     `json:"player,omitempty"`
	RadiantScore    *int64           `json:"radiant_score"`
	RadiantWin      *bool            `json:"radiant_win"`
	RegionID        *int64           `json:"region_id"`
	StartedAt       NullableDateTime `json:"started_at"`
}

type Provenance struct {
	Cache struct {
		AgeSeconds *int64 `json:"age_seconds"`
		Status     string `json:"status"`
	} `json:"cache"`
	DateRange *struct {
		From NullableDateTime `json:"from"`
		To   NullableDateTime `json:"to"`
	} `json:"date_range"`
	DetailLevel *string `json:"detail_level"`
	Operation   string  `json:"operation"`
	Patch       *struct {
		ID   *string `json:"id"`
		Name *string `json:"name"`
	} `json:"patch"`
	RateLimits []struct {
		Limit     *int64           `json:"limit"`
		Remaining *int64           `json:"remaining"`
		ResetAt   NullableDateTime `json:"reset_at"`
		Source    *string          `json:"source"`
		Window    string           `json:"window"`
	} `json:"rate_limits"`
	RetrievedAt   DateTime `json:"retrieved_at"`
	SchemaVersion string   `json:"schema_version"`
}

type QuerySuccess any

type Success struct {
	Data       map[string]any `json:"data"`
	Kind       string         `json:"kind"`
	Provenance Provenance     `json:"provenance"`
	Raw        any            `json:"raw,omitempty"`
	Summary    *string        `json:"summary"`
	Warnings   []string       `json:"warnings"`
}

type StratzExecuteGraphQLRequest struct {
	Cache           *bool          `json:"cache,omitempty"`
	CacheTTLSeconds *int64         `json:"cache_ttl_seconds,omitempty"`
	Fresh           *bool          `json:"fresh,omitempty"`
	OperationName   *string        `json:"operation_name,omitempty"`
	Query           string         `json:"query"`
	Variables       map[string]any `json:"variables,omitempty"`
}

type StratzExecuteGraphQLData struct {
	GraphQL struct {
		Data       any              `json:"data"`
		Errors     []map[string]any `json:"errors"`
		Extensions *map[string]any  `json:"extensions"`
	} `json:"graphql"`
	HTTPStatus int64 `json:"http_status"`
	Partial    bool  `json:"partial"`
}

type StratzExecuteGraphQLResponse ToolResult[StratzExecuteGraphQLData]

type StratzQueryConstantsRequest any

type StratzQueryConstantsData struct {
	Items any `json:"items,omitempty"`
	Mode  any `json:"mode,omitempty"`
}

type StratzQueryConstantsResponse ToolResult[StratzQueryConstantsData]

type StratzQueryHeroesRequest any

type StratzQueryHeroesData struct {
	Items any     `json:"items,omitempty"`
	Mode  *string `json:"mode,omitempty"`
}

type StratzQueryHeroesResponse ToolResult[StratzQueryHeroesData]

type StratzQueryLeaguesRequest any

type StratzQueryLeaguesData struct {
	Items any     `json:"items,omitempty"`
	Mode  *string `json:"mode,omitempty"`
}

type StratzQueryLeaguesResponse ToolResult[StratzQueryLeaguesData]

type StratzQueryMatchesRequest any

type StratzQueryMatchesData struct {
	Items any     `json:"items,omitempty"`
	Mode  *string `json:"mode,omitempty"`
}

type StratzQueryMatchesResponse ToolResult[StratzQueryMatchesData]

type StratzQueryPlayersRequest struct {
	Fresh                    *bool        `json:"fresh,omitempty"`
	IncludeProfileStatistics *bool        `json:"include_profile_statistics,omitempty"`
	IncludeRaw               *bool        `json:"include_raw,omitempty"`
	Mode                     string       `json:"mode"`
	PlayerIds                []Identifier `json:"player_ids"`
}

type StratzQueryPlayersData struct {
	Items any     `json:"items,omitempty"`
	Mode  *string `json:"mode,omitempty"`
}

type StratzQueryPlayersResponse ToolResult[StratzQueryPlayersData]

type StratzServerInfoRequest struct{}

type StratzServerInfoData struct {
	CacheStatus                  string         `json:"cache_status"`
	Limits                       map[string]any `json:"limits"`
	MCPProtocolVersion           string         `json:"mcp_protocol_version"`
	SchemaVersion                string         `json:"schema_version"`
	ServerVersion                string         `json:"server_version"`
	SupportedMCPProtocolVersions []string       `json:"supported_mcp_protocol_versions"`
	UpstreamStatus               string         `json:"upstream_status"`
}

type StratzServerInfoResponse ToolResult[StratzServerInfoData]

var generatedDefinitions = []Definition{
	{Name: "stratz_execute_graphql", Description: "Execute one guarded GraphQL query against an approved STRATZ root.", InputSchemaPath: "generated/schemas/stratz_execute_graphql.input.json", OutputSchemaPath: "generated/schemas/stratz_execute_graphql.output.json", InputExamplePath: "generated/examples/stratz_execute_graphql.input.json", OutputExamplePath: "generated/examples/stratz_execute_graphql.output.json", ProtocolFixturePath: "generated/protocol/stratz_execute_graphql.json"},
	{Name: "stratz_query_constants", Description: "Query supported constants by types or typed selectors.", InputSchemaPath: "generated/schemas/stratz_query_constants.input.json", OutputSchemaPath: "generated/schemas/stratz_query_constants.output.json", InputExamplePath: "generated/examples/stratz_query_constants.input.json", OutputExamplePath: "generated/examples/stratz_query_constants.output.json", ProtocolFixturePath: "generated/protocol/stratz_query_constants.json"},
	{Name: "stratz_query_heroes", Description: "Query normalized heroes exactly or by bounded search with optional statistics.", InputSchemaPath: "generated/schemas/stratz_query_heroes.input.json", OutputSchemaPath: "generated/schemas/stratz_query_heroes.output.json", InputExamplePath: "generated/examples/stratz_query_heroes.input.json", OutputExamplePath: "generated/examples/stratz_query_heroes.output.json", ProtocolFixturePath: "generated/protocol/stratz_query_heroes.json"},
	{Name: "stratz_query_leagues", Description: "Query normalized leagues exactly or by authenticated bounded search.", InputSchemaPath: "generated/schemas/stratz_query_leagues.input.json", OutputSchemaPath: "generated/schemas/stratz_query_leagues.output.json", InputExamplePath: "generated/examples/stratz_query_leagues.input.json", OutputExamplePath: "generated/examples/stratz_query_leagues.output.json", ProtocolFixturePath: "generated/protocol/stratz_query_leagues.json"},
	{Name: "stratz_query_matches", Description: "Query normalized matches by exact IDs, history filters, or live filters.", InputSchemaPath: "generated/schemas/stratz_query_matches.input.json", OutputSchemaPath: "generated/schemas/stratz_query_matches.output.json", InputExamplePath: "generated/examples/stratz_query_matches.input.json", OutputExamplePath: "generated/examples/stratz_query_matches.output.json", ProtocolFixturePath: "generated/protocol/stratz_query_matches.json"},
	{Name: "stratz_query_players", Description: "Query normalized players by one to 25 exact identifiers.", InputSchemaPath: "generated/schemas/stratz_query_players.input.json", OutputSchemaPath: "generated/schemas/stratz_query_players.output.json", InputExamplePath: "generated/examples/stratz_query_players.input.json", OutputExamplePath: "generated/examples/stratz_query_players.output.json", ProtocolFixturePath: "generated/protocol/stratz_query_players.json"},
	{Name: "stratz_server_info", Description: "Return server, protocol, schema, cache, limits, and upstream status.", InputSchemaPath: "generated/schemas/stratz_server_info.input.json", OutputSchemaPath: "generated/schemas/stratz_server_info.output.json", InputExamplePath: "generated/examples/stratz_server_info.input.json", OutputExamplePath: "generated/examples/stratz_server_info.output.json", ProtocolFixturePath: "generated/protocol/stratz_server_info.json"},
}
